# Allow kube-rbac-proxies to create tokenreviews to check Prometheus identity when scraping metrics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstack-cinder-kube-rbac-proxy-role
rules:
  - apiGroups:
    - authentication.k8s.io
    resources:
    - tokenreviews
    verbs:
    - create
