apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openstack-cinder-node-privileged-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openstack-cinder-privileged-role
subjects:
  - kind: ServiceAccount
    name: openstack-cinder-csi-driver-node-sa
    namespace: openshift-cluster-csi-drivers
