apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openstack-cinder-csi-storageclass-reader-resizer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-csi-resizer-storageclass-reader-role
subjects:
  - kind: ServiceAccount
    name: openstack-cinder-csi-driver-controller-sa
    namespace: openshift-cluster-csi-drivers
