apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: openstack-cinder-csi-driver-controller-metrics-serving-cert
  labels:
    app: openstack-cinder-csi-driver-controller-metrics
  name: openstack-cinder-csi-driver-controller-metrics
  namespace: openshift-cluster-csi-drivers
spec:
  ports:
    - name: provisioner-m
      port: 443
      protocol: TCP
      targetPort: provisioner-m
    - name: attacher-m
      port: 444
      protocol: TCP
      targetPort: attacher-m
    - name: resizer-m
      port: 445
      protocol: TCP
      targetPort: resizer-m
    - name: snapshotter-m
      port: 446
      protocol: TCP
      targetPort: snapshotter-m
  selector:
    app: openstack-cinder-csi-driver-controller
  sessionAffinity: None
  type: ClusterIP
